source 'http://rubygems.org'

gem 'capybara'
gem 'cucumber'
gem 'cucumber_statistics'
gem 'mail'
gem 'mime-types'
gem 'net-ssh'
gem 'oga'
gem 'parallel_tests'
gem 'rest-client'
gem 'rspec'
gem 'selenium-webdriver'
gem 'show_me_the_cookies'
gem 'terminal-table'
gem 'json-compare'
gem 'yajl'
gem 'capybara-screenshot'